version: '3'
services:
  nuxt:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    environment:
      - HOST=0.0.0.0
      - PORT=3000
    volumes:
      - ./:/workspace
    tty: true