<template>
  <PostListTemplate :data="data" />
</template>

<script lang="ts" setup>
import PostListTemplate, { PostListTemplateData } from '~/components/templates/PostListTemplate.vue'

const data = ref({
  posts: []
} as PostListTemplateData)

onMounted(() => {
  import('~/autogenerated/articles').then((o) => {
    data.value.posts = o.articles
  })
})
</script>

<style>

</style>
